name: Kai.Simon
favicon: null
layout_spectrum: 0.24680735915899277
typography_spectrum: 0.6538516192231327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.625
  lightness: 0.6918458756990731
  saturation: 0.27032522461377084
  rhythmicContrast: 0.16806678380817175
purpose: []
